on:
  push:
    branches:
      - feature/actions-deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.95.0'

      - name: Build
        run: hugo --minify

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftpServer }}
          username: ${{ secrets.ftpUsername }}
          password: ${{ secrets.ftpPassword }}
          server-dir: ${{ secrets.ftpDir }}
          local-dir: ./public/